= Proof of Concept for federated, connected eID System for iOS

WARNING: This software is merely a *functional* proof of concept. It supposed toishow the basic flows and integration options for clients, identity providers and relying parties.

== Pre-Requisites


I recommend using HTTPie (https://httpie.org) over curl 

Install Python 3.8 (e.g. apt-get or brew install)

Install Docker (optional)

== Use the public API

See the API docs under https://acme.spilikin.dev/api/docs/

[source,bash]
----
https acme.spilikin.dev/api/info 
----

.Enroll using the python client
[source,bash]
----
cd healthid/cli
# start the python virtual environment
source venv.sh
# choose your account name. it must be in email format
ACCT=<test email address>
# enroll 
./enroll.py --endpoint https://acme.spilikin.dev/api/ $ACCT
# see ECC key files
ls -alR ./accounts/
# verbose authentication
./auth.py --verbose --endpoint https://acme.spilikin.dev/api/ $ACCT
# get token to ENV variable
TOKEN=`./auth.py --endpoint https://acme.spilikin.dev/api/ $ACCT`
echo $TOKEN
# access protected resource
https "https://acme.spilikin.dev/api/acct/$ACCT" "Authorization:Bearer $TOKEN"

----

== Run API locally

You will need Python 3.8 (install using apt-get oder brew install)

.Start HealthID API Server
[source,bash]
----
cd healthid/api
source venv.sh
uvicorn healthid:app --reload
http localhost:8000/api/info 
----



== Actors, Domains and Deep Links

=== Acme Administration
    acme.spilikin.dev
    id.acme.spilikin.dev
    appauth.acme.spilikin.dev

=== Foo Insurances
    foo.spilikin.dev
    id.foo.spilikin.dev
    appauth.foo.spilikin.dev

=== Bar Benefitial
    bar.spilikin.dev
    id.bar.spilikin.dev
    appauth.bar.spilikin.dev

=== Qux Medical
    qux.spilikin.dev

== Running locally

.Start UI Server
----
cd healthid/vue
yarn serve
open http://127.0.0.1:8080/SignIn
----


.Create Docker image
----
cd healthid
docker build . -t healthid
----

.Run Docker image
----
cd healthid
docker run -it -p 80:80 --rm healthid 
----
